#!/bin/bash

if [ ! -f ${FACTORIO_SAVEGAME} ]; then
  echo "No save game found; creating savegame.zip."
  /opt/factorio/bin/x64/factorio --create ${FACTORIO_SAVEGAME}
fi

/opt/factorio/bin/x64/factorio --start-server ${FACTORIO_SAVEGAME}